# Generated by Django 4.2.3 on 2023-07-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=100)),
                ('purchaseDate', models.DateField()),
            ],
        ),
    ]
