# Generated by Django 4.2.3 on 2023-07-17 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='name',
        ),
        migrations.AddField(
            model_name='production',
            name='liters',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25)], default=1, max_length=2),
        ),
    ]
