# Generated by Django 4.2.3 on 2023-07-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0003_alter_production_liters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='liters',
            field=models.DecimalField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (10, 10), (15, 15), (20, 20), (25, 25)], decimal_places=1, default=1, max_digits=3),
        ),
    ]
