# Generated by Django 4.2.3 on 2023-07-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0004_alter_production_liters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='purchaseDate',
            new_name='production_Date',
        ),
    ]
