# Generated by Django 4.2.3 on 2023-07-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Production', '0005_rename_purchasedate_production_production_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='total',
            field=models.PositiveIntegerField(),
        ),
    ]
